export const Docs =[
    {
        title:' Convert PDF to Word',
        end_title:"Endpoints",
        end_url:'POST /pdf_to_word/{user_id}',
        desc_title:'Convert PDF to Word',
        desc_content:'Converts a PDF document to a Word document (.docx).',
        req_header:'Request Headers:',
        req_url:'Api-Key: Your API key',
        req_param:'Request Parameters:',
        req_par_content:'user_id: The ID of the user',
        req_body:'Request Body:',
        req_body_file:'file: The PDF file to be converted.',
        res_title:'Response:',
        // res_content:'res',
        res_content:` "result": {
            "id": File id,
            "file": "Original file uploaded",
            "converted_file_url": "Processed file url to download",
            "uploaded_at": "The day file uploaded and processed"
          },
          "file_name": "The processed file name"`,
        example_use_title:'Example usage:',
        example_use_content:'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/api/rotate_pdf/123/'
    },
]

export const Endpoints = [
    {
      title: 'Convert PDF to Word',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_word/{user_id}',
      desc_title: 'Convert PDF to Word',
      desc_content: 'Converts a PDF document to a Word document (.docx).',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_word/123/"'
    },
    {
      title: 'Convert PDF to Excel',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_excel/{user_id}',
      desc_title: 'Convert PDF to Excel',
      desc_content: 'Converts a PDF document to an Excel spreadsheet (.xlsx).',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_excel/123/"'
    },
    {
      title: 'Convert PDF to JPG',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_jpg/{user_id}',
      desc_title: 'Convert PDF to JPG',
      desc_content: 'Converts a PDF document to JPG images.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_jpg/123/"'
    },
    {
      title: 'Convert PDF to PNG',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_png/{user_id}',
      desc_title: 'Convert PDF to PNG',
      desc_content: 'Converts a PDF document to PNG images.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_png/123/"'
    },
    {
      title: 'Convert PDF to JPEG',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_jpeg/{user_id}',
      desc_title: 'Convert PDF to JPEG',
      desc_content: 'Converts a PDF document to JPEG images.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_jpeg/123/"'
    },
    {
      title: 'Convert PDF to CSV',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_csv/{user_id}',
      desc_title: 'Convert PDF to CSV',
      desc_content: 'Converts a PDF document to a CSV file.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_csv/123/"'
    },
    {
      title: 'Convert PDF to BMP',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_bmp/{user_id}',
      desc_title: 'Convert PDF to BMP',
      desc_content: 'Converts a PDF document to BMP images.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_bmp/123/"'
    },
    {
      title: 'Convert PDF to PPT',
      end_title: 'Endpoints',
      end_url: 'POST /pdf_to_ppt/{user_id}',
      desc_title: 'Convert PDF to PPT',
      desc_content: 'Converts a PDF document to a PowerPoint presentation (.pptx).',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/pdf_to_ppt/123/"'
    },
    {
      title: 'Convert Excel to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /excel_to_pdf/{user_id}',
      desc_title: 'Convert Excel to PDF',
      desc_content: 'Converts an Excel spreadsheet to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The Excel file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.xlsx" " http://yourdomain.com/excel_to_pdf/123/"'
    },
    {
      title: 'Convert CSV to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /csv_to_pdf/{user_id}',
      desc_title: 'Convert CSV to PDF',
      desc_content: 'Converts a CSV file to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The CSV file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.csv" " http://yourdomain.com/csv_to_pdf/123/"'
    },
    {
      title: 'Convert Image to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /image_to_pdf/{user_id}',
      desc_title: 'Convert Image to PDF',
      desc_content: 'Converts an image file (JPG, PNG, etc.) to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The image file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.jpg" " http://yourdomain.com/image_to_pdf/123/"'
    },
    {
      title: 'Convert PPT to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /ppt_to_pdf/{user_id}',
      desc_title: 'Convert PPT to PDF',
      desc_content: 'Converts a PowerPoint presentation to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PPT file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@presentation.pptx" " http://yourdomain.com/ppt_to_pdf/123/"'
    },
    {
      title: 'Convert Word to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /word_to_pdf/{user_id}',
      desc_title: 'Convert Word to PDF',
      desc_content: 'Converts a Word document to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The Word file to be converted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.docx" " http://yourdomain.com/word_to_pdf/123/"'
    },
    {
      title: 'Extract PDF',
      end_title: 'Endpoints',
      end_url: 'POST /edit/extract-pdf/{user_id}',
      desc_title: 'Extract PDF',
      desc_content: 'Extracts pages from a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be extracted.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/extract-pdf/123/"'
    },
    {
      title: 'Remove PDF Page',
      end_title: 'Endpoints',
      end_url: 'POST /edit/remove-page/{user_id}',
      desc_title: 'Remove PDF Page',
      desc_content: 'Removes a specific page from a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file from which the page will be removed.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/remove-page/123/"'
    },
    {
      title: 'Add Page to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /edit/add-page/{user_id}',
      desc_title: 'Add Page to PDF',
      desc_content: 'Adds a page to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to which the page will be added.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/add-page/123/"'
    },
    {
      title: 'Repair PDF',
      end_title: 'Endpoints',
      end_url: 'POST /edit/repair-pdf/{user_id}',
      desc_title: 'Repair PDF',
      desc_content: 'Repairs a corrupted PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The corrupted PDF file to be repaired.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/repair_pdf/123/"'
    },
    {
      title: 'Rotate PDF',
      end_title: 'Endpoints',
      end_url: 'POST /edit/rotate-pdf/{user_id}',
      desc_title: 'Rotate PDF',
      desc_content: 'Rotates pages in a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file with pages to be rotated.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/rotate_pdf/123/"'
    },
    {
      title: 'Add Watermark to PDF',
      end_title: 'Endpoints',
      end_url: 'POST /edit/add-watermark/{user_id}',
      desc_title: 'Add Watermark to PDF',
      desc_content: 'Adds a watermark to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to which the watermark will be added.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/add_watermark/123/"'
    },
    {
      title: 'Compress PDF',
      end_title: 'Endpoints',
      end_url: 'POST /optimize/compress-pdf/{user_id}',
      desc_title: 'Compress PDF',
      desc_content: 'Compresses a PDF document to reduce its file size.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be compressed.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/compress_pdf/123/"'
    },
    {
      title: 'Merge PDF',
      end_title: 'Endpoints',
      end_url: 'POST /optimize/merge-pdf/{user_id}',
      desc_title: 'Merge PDF',
      desc_content: 'Merges multiple PDF documents into a single PDF file.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'files: The PDF files to be merged.',
      res_title: 'Response:',
      res_content: `
      "result": {
          "id": File id,
          "file": "Original files uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day files uploaded and processed"
        },
        "file_name": "The processed file name"
      `,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "files=@document1.pdf" -F "files=@document2.pdf" " http://yourdomain.com/merge_pdf/123/"'
    },
    {
      title: 'Split PDF',
      end_title: 'Endpoints',
      end_url: 'POST /optimize/split-pdf/{user_id}',
      desc_title: 'Split PDF',
      desc_content: 'Splits a PDF document into multiple PDF files.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be split.',
      res_title: 'Response:',
      res_content: `
      "result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed files url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"
      `,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/split_pdf/123/"'
    },
    {
      title: 'Protect PDF',
      end_title: 'Endpoints',
      end_url: 'POST /secure/protect-pdf/{user_id}',
      desc_title: 'Protect PDF',
      desc_content: 'Adds password protection to a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The PDF file to be protected.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/protect_pdf/123/"'
    },
    {
      title: 'Unlock PDF',
      end_title: 'Endpoints',
      end_url: 'POST /secure/unlock-pdf/{user_id}',
      desc_title: 'Unlock PDF',
      desc_content: 'Removes password protection from a PDF document.',
      req_header: 'Request Headers:',
      req_url: 'Api-Key: Your API key',
      req_param: 'Request Parameters:',
      req_par_content: 'user_id: The ID of the user',
      req_body: 'Request Body:',
      req_body_file: 'file: The protected PDF file to be unlocked.',
      res_title: 'Response:',
      res_content: `"result": {
          "id": File id,
          "file": "Original file uploaded",
          "converted_file_url": "Processed file url to download",
          "uploaded_at": "The day file uploaded and processed"
        },
        "file_name": "The processed file name"`,
      example_use_title: 'Example usage:',
      example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/unlock_pdf/123/"'
    },
    {
        title: 'Digital signature',
        end_title: 'Endpoints',
        end_url: 'POST /digital_signature/{user_id}',
        desc_title: 'Digital signature',
        desc_content: 'Sign the document digitally.',
        req_header: 'Request Headers:',
        req_url: 'Api-Key: Your API key',
        req_param: 'Request Parameters:',
        req_par_content: 'user_id: The ID of the user',
        req_body: 'Request Body:',
        req_body_file: 'file: The file to be sign.',
        res_title: 'Response:',
        res_content: `
        "result": {
            "id": File id,
            "file": "Original file uploaded",
            "converted_file_url": "Processed file url to download",
            "uploaded_at": "The day file uploaded and processed"
          },
          "file_name": "The processed file name"
        `,
        example_use_title: 'Example usage:',
        example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/digital_signature/123/"'
      },
      {
        title: 'Verify digital signature',
        end_title: 'Endpoints',
        end_url: 'POST /secure/verify_digital_signature/{user_id}',
        desc_title: 'Verify digital signature',
        desc_content: 'Verify digital signature for any document document.',
        req_header: 'Request Headers:',
        req_url: 'Api-Key: Your API key',
        req_param: 'Request Parameters:',
        req_par_content: 'user_id: The ID of the user',
        req_body: 'Request Body:',
        req_body_file: 'file: The digitally signed file.',
        res_title: 'Response:',
        res_content: `
        "result": {
            "id": File id,
            "file": "Original file uploaded",
            "converted_file_url": "Processed file url to download",
            "uploaded_at": "The day file uploaded and processed"
          },
          "file_name": "The processed file name"
        `,
        example_use_title: 'Example usage:',
        example_use_content: 'curl -X POST -H "Api-Key: your_api_key" -F "file=@document.pdf" " http://yourdomain.com/verify_digital_signature/123/"'
      },
]